### ISSUE TITLE
Using Handlebar helpers inside of template that is dynamically rendered by API call?

### ISSUE THREAD

**Issue by aaronksaunders** [keystonejs/keystone-demo#15]
when i run the code below, none of  the helpers that are in the template work? How do i load the helpers or is there another way I should be doing this in Keystone?

I posted this issue here since it is a demo of handlebars, but if it should be in main repo, I will move it.

the template

``` html
    <script id="test-template" type="text/x-handlebars-template">
        \{{#each data.jobs.results}}
        <!-- Every Post -->
        <div class="col-sm-5 jobs-card loop">
            <a data-toggle="modal" data-target="#myModal" data-remote="\{{postUrl slug}} #fragment"
               href="\{{postUrl slug}}">
                <div class="jobs-image">
                    <img alt="\{{{title}}}" class="img-thumbnail"
                         src="{{#if image.url}}{{cloudinaryUrl image width=80 height=80 crop='fill' gravity='center' }}{{else}}
        /html/assets/tumblr_mufrp1cpsZ1st5lhmo1_1280.jpg{{/if}}"/>
                </div>

                <div class="jobs-content">
                    <h3 class="jobs-content-header">\{{{ title}}}</h3>

                    <p class="jobs-content-copy">\{{{shortDescription}}}</p>

                </div>

                <div class="jobs-share">

                </div>

            </a>
        </div>
        <!-- /.col-sm-6-->
        \{{/each}}
    </script>
```

The source code

``` javascript
      $("#selectedCategory").change(function (_event) {

            var url;
            if (_event.target.value) {
                url = 'http://localhost:3000/api/postByCategory/' + _event.target.value;
            } else {
                url = 'http://localhost:3000/api/post';
            }

            $.ajax({
                url: url,
                dataType: 'json',
                success: function (_response) {
                    try {
                        var source = $('#test-template').html();
                        var template = Handlebars.compile(source);
                        var context = {
                            data: {
                                jobs: {
                                    results: _response.Posts
                                }
                            }
                        };
                        var html = template(context);
                        $('#jobCardSection').html(html);
                    } catch (EE) {
                        console.log(EE);
                    }
                }
            });
        });
```

**Comment by morenoh149** [comment]
is using jade at all an option? It may sound fickle but I have more experience with it :P

**Comment by aaronksaunders** [comment]
If you can point me to a workable solution I will have to consider it since
we are completely blocked now

On Thursday, February 26, 2015, Harry Moreno <notifications@github.com>
wrote:

> is using jade at all an option? It may sound fickle but I have more
> experience with it :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JedWatson/keystone-demo/issues/15#issuecomment-76289670>
> .
>


-- 
-- <http://www.clearlyinnovative.com/build-it/>
--

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
201.214.5926  (M)
blog@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders





This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by morenoh149** [comment]
Try printing the value of `data.jobs.results` in your template as a sanity check. Before the `each` loop. Also enable syntax highlighting in your question by adding
```
 ```javascript or ```html
```
to your snippets after the first triplet of grave accents (`)

**Comment by aaronksaunders** [comment]
I am getting the data in the page/template correctly, the issue is that I don't have access to the Handlebars partials or the handlebar helpers that are created for managing posts and cloudinary

**Comment by morenoh149** [comment]
did you specify handlebars your project like this? http://keystonejs.com/docs/getting-started/#templates_other

So you're seeing multiple `<div class="col-sm-5 jobs-card loop">` in your page right? they're just missing fields where the hanldebars helpers are called? Share the rendered html.

**Comment by aaronksaunders** [comment]
The handlebars are rendering fine...until i try to update the page using $ajax

The issue is that I am trying to updated the list dynamically when the user selects a different category of information.

I attempted to use a partial, compile it and then update the DOM... that fails because I cannot access the partials and I cannot access the helpers when compiling the templates in the javascript

**Comment by jstockwin** [comment]
Closing this as it's so old and we're trying to keep our issue trackers unpolluted. If you still need help with this feel free to re-open.
