### ISSUE TITLE
Fileupload

### ISSUE THREAD

**Issue by porschuetz** [keystonejs/keystone-demo#17]
Hello Everybody,

this is a super interesting starting point. Love to see the project grow and contribute as good as possible.

I got a quick starter question and google didn't help yet.

GET /keystone/galleries/54f607729866aaaf0a04dabf 200 1321ms
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

/Users/dannydevelop/www/sandbox/keystone-demo/node_modules/keystone/node_modules/cloudinary/lib/utils.coffee:574
        throw "Must supply api_key";
        ^
Must supply api_key

what API is talked about?

Best, Tilman

**Comment by jstockwin** [comment]
Closing this as it's so old and we're trying to keep our issue trackers unpolluted. 
Sorry that nobody ever responded to this. The api_key was probably for Cloudinary. If you still need help please do reopen this issue.
