### ISSUE TITLE
Protect the demo user from being disabled

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-demo#2]
At the moment, the isAdmin flag can be edited, which lets people disable the demo account. Not good.

**Comment by bradoyler** [comment]
I can't login to demo site @ http://demo.keystonejs.com/keystone 
Is this project still maintained?

**Comment by JedWatson** [comment]
@bradoyler sure is! looks like something went wrong with our Demo Account protection, I've fixed that up and will stop it happening again :)
