### ISSUE TITLE
Can't launch demo.

### ISSUE THREAD

**Issue by pippintook** [keystonejs/keystone-demo#23]
![screenshot 2015-10-04 at 15 32 03](https://cloud.githubusercontent.com/assets/11688445/10266513/2d82c248-6aad-11e5-89ea-a10bf138f322.png)

**Comment by pixelfreak** [comment]
The demo page has been down for days. Is anyone fixing it? Not a great page to give confidence to new users...

**Comment by jossmac** [comment]
On it right now :)

There was an issue with mongoose/heroku. We're taking this opportunity to fix a few things and move it to the KeystoneJS repo. I'll leave this open until we push the changes online

**Comment by jossmac** [comment]
Back online: http://demo.keystonejs.com

**Comment by pixelfreak** [comment]
Nice! Thank you

**Comment by jossmac** [comment]
@pixelfreak no problem!

Thought I'd repay the favour http://www.williamkhoe.com appears to be down

**Comment by pixelfreak** [comment]
The irony ;) That site hasn't existed for a while coz it has zero purpose. Profile updated!
