### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by cauburtin** [keystonejs/keystone-demo#25]
after signin up, I couldn't access to the Admin UI, neither add posts, redirected to signin

**Comment by rafamontoya** [comment]
+1

**Comment by JamesLeBoeuf** [comment]
+1

**Comment by klarkc** [comment]
+1

**Comment by jossmac** [comment]
@cauburtin @rafamontoya @JamesLeBoeuf @klarkc 

Unable to reproduce. Please attempt [sign in](http://demo.keystonejs.com/keystone/signin) with the credentials:
```
demo@keystonejs.com
demo
```

Let me know if this is still an issue

**Comment by klarkc** [comment]
It's working here
