### ISSUE TITLE
npm install throwing an error on ubuntu

### ISSUE THREAD

**Issue by amititash** [keystonejs/keystone-demo#26]
Hi, 

I am getting the following error when trying to install on ubuntu. 

200 https://github.com/keystonejs/keystone.git
npm http 200 https://registry.npmjs.org/async
npm ERR! not a package /home/ubuntu/tmp/npm-1507-LOv47Z7N/1448914559088-0.12499654735438526/tmp.tgz
npm ERR! Error: ENOENT, open '/home/ubuntu/tmp/npm-1507-LOv47Z7N/1448914559088-0.12499654735438526/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

It seems to work fine on my local mac but not on my amazon ec2 ubuntu server running 14.04

Please help.

Thanks
Titash

**Comment by quitequinn** [comment]
Try npm install -g npm@latest
https://github.com/npm/npm/issues/11970

**Comment by quitequinn** [comment]
How do we contact someone to close an issue once its solved?

**Comment by jstockwin** [comment]
@amititash I'm going to close this as it's so old and you've not responded to the above. If you're still having issues with this, feel free to re-open this and detail the problem.
