### ISSUE TITLE
credentials not working

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone-demo#30]
demo@keystonejs.com/demo was changed

from https://github.com/keystonejs/keystone/issues/2069

**Comment by radiovisual** [comment]
When I attempt to use the following login credentials on the [Keystone Admin Demo](http://demo.keystonejs.com/keystone/signin):

username: `demo@keystonejs.com`
password: `demo`

I get the following error:
> The email and password you entered are not valid.

I also tried the combination of keystone/keystone with no luck.

**Comment by JedWatson** [comment]
Fixed.

**Comment by swapdewalkar** [comment]
Still have problem not able to login. Same Error

**Comment by JakielaAdam** [comment]
+1

**Comment by Noviny** [comment]
Refixed this today, and should have ensured people can't break it again. Unless they're really cunning.
