### ISSUE TITLE
Accept any credentials to log in

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/keystone-demo#34]
We should change the logic to accept any email/password so we don't have to keep resetting the credentials.

Re https://github.com/keystonejs/keystone/issues/2137

**Comment by morenoh149** [comment]
alternatively, if we integrate oauth with google plus that would solve the vandalism issue altogether

**Comment by jstockwin** [comment]
@morenoh149 The credentials are now [protected](https://github.com/keystonejs/keystone-demo/blob/master/updates/0.0.1-admins.js#L13), so this is no longer an issue, correct?

**Comment by jstockwin** [comment]
Reopen this if you disagree with the above - I'm trying to clear up the issue tracker.

**Comment by fancyoung** [comment]
Still show `The email and password you entered are not valid.` when use `demo@keystonejs.com / demo` login.

**Comment by jstockwin** [comment]
Yeah, I agree. I can't log in to the demo site at the moment. @bassjacob / @JedWatson ?
