### ISSUE TITLE
Default Date is Invalid in Gallery

### ISSUE THREAD

**Issue by chrislewispac** [keystonejs/keystone-demo#35]
Default date in gallery upload section in admin ui is in format:

27th Jan 2016

Causing a flash error message:

```
There was a problem saving your changes:
Please enter a valid date in the Published Date field
```

needs to be in format

2016-01-27

**Comment by jstockwin** [comment]
This seems to be fixed in current master, so I'm closing this issue. Please re-open if you disagree.
