### ISSUE TITLE
Cannot get comments to post

### ISSUE THREAD

**Issue by shanepisko** [keystonejs/keystone-demo#36]
I am working on implementing the postcomment feature, however when I submit a comment i get a 404 error from the post method of the comment form. I have copied over the post.js, the commenting mixins, and the post comment model. What am i missing?

**Comment by shanepisko** [comment]
I figured it out! in my routes/index.js my page_router that was built from a separate tutorial was set to only .get, i switched it to all and now commenting is working!

**Comment by EduardoAC** [comment]
@shanepisko  then you should close this issue and keep the record so people like me can save some time when it's trying to replicate the comment feature
