### ISSUE TITLE
Unnecessary line in route/view/post.js

### ISSUE THREAD

**Issue by EduardoAC** [keystonejs/keystone-demo#37]
Hi @JedWatson. 

I was using your comments feature that you show in this keystone-demo project and I may spotted a unnecessary variable that you don't use in the whole file.

I want to verify that is correct or not before I submit my [pull request](https://github.com/EduardoAC/keystone-demo/tree/unnecesary-line-in-route-view-post)

[https://github.com/EduardoAC/keystone-demo/blob/master/routes/views/post.js#L2](https://github.com/EduardoAC/keystone-demo/blob/master/routes/views/post.js#L2)

**Comment by jossmac** [comment]
Please submit for Post. `async` is in use for Blog https://github.com/EduardoAC/keystone-demo/blob/master/routes/views/blog.js#L31

**Comment by EduardoAC** [comment]
@jossmac Done, Thanks for the feedback.
