### ISSUE TITLE
Choose between different templates in posts wysiwyg editor

### ISSUE THREAD

**Issue by tpgmartin** [keystonejs/keystone-demo#39]
I’m interested to know how I can choose between templates in the wysiwyg editor, corresponding to different post variations. For instance in the post model from the demo it has a content property with a "brief" and "extended" field. How could I add optional fields to this model? 

Relatedly, how could I let the user select between different styles for different type of post layouts, designs etc.?

Cheers

**Comment by jossmac** [comment]
Please see [Admin UI Options](http://keystonejs.com/docs/configuration/#options-ui)
