### ISSUE TITLE
Some pages are broken on Safari 8

### ISSUE THREAD

**Issue by mxstbr** [keystonejs/keystone-demo#42]
> After login this page is blank
>  http://demo.keystonejs.com/keystone/posts
>  It works fine on Chrome
>  p/s: seem others link blank too http://demo.keystonejs.com/keystone/enquiries

— @nvcken ([src](https://github.com/keystonejs/keystone/issues/2443))

@vitalbone replicated the issue, this is a bug and should be fixed. Getting this error: 

```
SyntaxError: Attempted to redefine property 'downloadItems'.
(anonymous function)list.js:5786
list.js:5786
```

**Comment by jstockwin** [comment]
@mxstbr This issue is very old - is it still a problem?

**Comment by mxstbr** [comment]
No idea, I no longer even have Safari 8!

**Comment by jstockwin** [comment]
Alright. This is super old so I'm just going to close it. If anyone encounters this then please re-open the issue and give details.
