### ISSUE TITLE
The email and password you entered are not valid.

### ISSUE THREAD

**Issue by philohelp** [keystonejs/keystone-demo#46]
I modified the 0.0.1-admins.js file but I get an error message when I try to sign in. Its sad because I'd really love to work with this great version.

**Comment by sonali0901** [comment]
I would like t work towards solving this bug, Some idea as of what to do ?

**Comment by jossmac** [comment]
The `0.0.1-admins.js` file is an "update script", update scripts are run once when the database is initialised.

If you cloned this repo the email/password combination will be:
```
demo@keystonejs.com
demo
```

You should be able to sign in with those details then create a new user with your desired info

**Comment by sonali0901** [comment]
The sign in is successful with given credentials. Also creating new user too. The bug states problem when changing credentials for admin sign in, If I understood right?. So need to try by making changes in the 0.0.1-admins.js and see whats the error?

**Comment by jstockwin** [comment]
This was duplicated by #59, which I've now closed. See the comments there for how to fix this when cloning the demo site.
