### ISSUE TITLE
Mandrill required paid monthly MailChimp by April 27

### ISSUE THREAD

**Issue by katopz** [keystonejs/keystone-demo#47]
Hi guys,

I'm try to build demo today and sadly found this [announement](http://blog.mandrill.com/important-changes-to-mandrill.html?_ga=1.267553421.2029528845.1459272696).
Maybe it's time to switch to [mailgun](https://www.mailgun.com/pricing) instead?

Thanks.

**Comment by mxstbr** [comment]
Mailgun is already implemented, both in the latest `0.3.x` and the current master version of Keystone!
