### ISSUE TITLE
XSS on comments

### ISSUE THREAD

**Issue by juan-manuel-alberro** [keystonejs/keystone-demo#48]
Hello,

You can inject `Javascript` in your post comments, take a look in here - http://demo.keystonejs.com/blog/post/another-post#comment-id-5716127eb541d30300b33620

I think you need to fix this **ASAP**,
Cheers.

**Comment by geloescht** [comment]
There used to be an issue on that, I thought it was closed...

**Comment by stennie** [comment]
Looks like this was fixed by @morenoh149's commits from 2016, but never closed. If there are still any outstanding problems please create a new GitHub issue.

Thanks,
Stennie
