### ISSUE TITLE
Clicking on comment while on post page leads to 404

### ISSUE THREAD

**Issue by pravk** [keystonejs/keystone-demo#51]
I cloned the repo and launched the app on localhost. I created a post and added a comment for the post. 
Now when I click on the comment id while on post page, it gives an error

"There's a problem with the network, we're trying to reconnect...".

The following XHR request to the server keeps failing:
GET /keystone/api/posts/573ab3a8da4bb04f3044cfe4?drilldown=true 404 3.952 ms
is throwing
{"err":"not found","id":"573ab3a8da4bb04f3044cfe4"}

I noticed that the id passed is that of the comment, hence 404.

Also please note that on refresh the page loads perfectly fine.

Thanks
Praveen

**Comment by bjwyse** [comment]
Seems to refer to outdated functionality.

I could not click on a comment to view it separately. There is a link to delete the comment, which works fine.

**Comment by jstockwin** [comment]
I agree with the above comment here, so I'm closing this. Let me know if we're misunderstanding though and we can re-open it.
