### ISSUE TITLE
Upon updating an existing post publish date doesn't display

### ISSUE THREAD

**Issue by Willberforce** [keystonejs/keystone-demo#53]
Upon updating an existing post the publish date doesn't display again - the console logs the following error from this line...
`field = undefined, path = "createdAt"`
...from the following line...
`console.warn('Invalid Column specified:', i);`
...within item.js

The error is thrown whilst looking for "createdAt" within the fields array.

`var field = _this.fields[path];`

This is whilst updating an existing post on this webpage http://demo.keystonejs.com/keystone/posts/

**Comment by bjwyse** [comment]
Not reproducible in latest demo code.

**Comment by jstockwin** [comment]
I agree with the above comment, all seems fine to me. I'm trying to sort through all the current issues, so am going to close this. 

If you're still having problems, please reopen and give more details. Thanks!
