### ISSUE TITLE
Seeing How Demo Was Built

### ISSUE THREAD

**Issue by artforlife** [keystonejs/keystone-demo#54]
Is there a place where one can see how this demo was built? I can follow the Getting Started guide, but there seems to be too much of a gap between what is offered there and this "basic" demo. Any suggestions are appreciated. 
P.S. Awesome CMS!

**Comment by jstockwin** [comment]
@artforlife: It's probably quite unlikely that anyone is going to have the time to do this, I'm afraid. It's not intended to be a guide on how to create keystone apps, but as a demo of what keystone can do. We're currently working on new documentation and guides, that should hopefully help with this.

If you still need help, where do you think the 'gap' is? What are you struggling with? 
If you've worked it out, can we close this issue?

**Comment by stennie** [comment]
For more information on building your own apps with Keystone, see: [KeystoneJS: Getting Started](http://keystonejs.netlify.com/getting-started).
