### ISSUE TITLE
Why dotenv removed

### ISSUE THREAD

**Issue by LucasIcarus** [keystonejs/keystone-demo#55]
I notice that dotenv has been removed since 2015.11.. 

The ones who clone this repo and try to build their own project based on it need to install it by themselves or there is some other module replace the dotenv?

I'm just curious about that and if this issue is not proper plz let me konw and I will close it anyway.

**Comment by bjwyse** [comment]
This file was not necessary to run the demo for me.

**Comment by jstockwin** [comment]
Likewise, I did not need `dotenv` to run the site. I'm going to close this, but if you still think it's an issue please re-open with more details (e.g. what exactly is requiring dotenv?)
