### ISSUE TITLE
TypeError: Object #<Object> has no method 'accessSync'

### ISSUE THREAD

**Issue by mepawan** [keystonejs/keystone-demo#56]
Hi, 

I have setup this demo and I have tried to use Types.File. But when I tried to start keystone I'm getting this error: 
`/home/ubuntu/kslms/lms/node_modules/keystone/lib/storage/adapters/fs/index.js:36
		throw e;
		      ^
TypeError: Object #<Object> has no method 'accessSync'
    at ensurePath (/home/ubuntu/kslms/lms/node_modules/keystone/lib/storage/adapters/fs/index.js:24:6)
`
**Here is my code:** 
`var MediaStorage = new keystone.Storage({
  adapter: keystone.Storage.Adapters.FS,
  fs: {
    path: keystone.expandPath('./uploads'),
    publicPath: '/public/uploads',
  },
});
SectionLession.add({
	title: { type: String, required: true },
	section: { type: Types.Relationship, initial: true, ref: 'CourseSection', index: true },
	banner: { type: Types.CloudinaryImage },
	content:{ type: Types.Html, wysiwyg: true, height: 400 },
	files: { type: Types.File, storage: MediaStorage },
	author: { type: Types.Relationship, initial: true, ref: 'User', index: true },
	state: { type: Types.Select, options: ['published', 'draft', 'archived'], default: 'published', index: true },
});`

**nodejs version is v0.10.46**

can anyone help me to fix this issue?

thanks,

**Comment by mxstbr** [comment]
Use Node > 0.10. Node 0.10 hasn't been supported in a long time – in fact, node 6 is the current version!
