### ISSUE TITLE
Contact Page - propery validationErrors.name  not found

### ISSUE THREAD

**Issue by mepawan** [keystonejs/keystone-demo#57]
Hi,

I have setup this dome to my server. Here is url: 
http://52.38.37.147:3000/contact

when I submit contact us (enquiry) form I'm getting errror that propery 'name' not found. Here is full error info: 
![screenshot from 2016-08-27 17 29 29](https://cloud.githubusercontent.com/assets/3142483/18027244/8e044b88-6c7c-11e6-8104-a7fb7699f9e8.png)

Can anyone help me to fix this issue?

Thanks,

**Comment by mxstbr** [comment]
As the error message says, you probably deleted the part that injects `validationErrors` via the locals: https://github.com/keystonejs/keystone-demo/blob/235bf86dc9e65c5e4eb294147e304df7a8aa92b1/routes/views/contact.js#L24
