### ISSUE TITLE
Unable to login to the demo with given credentials

### ISSUE THREAD

**Issue by aleixfabra** [keystonejs/keystone-demo#59]
Sign in with the username `demo@keystonejs.com` and the password `demo`

**Comment by tmartin2089** [comment]
Same problem.  Confirmed in DB that username and password are correct.

**Comment by n-lavrenko** [comment]
**+1**
Also I get **500 error** and response:
```
{
  detail: "Not a valid BCrypt hash.",
  error: "bcrypt error"
}
```

I think the problem is in password validation rules: the basic password is plain text: ```'demo'```
We need to encrypt password and replace ```'demo'``` in /updates/0.0.1-admins.js to encrypted password.

**Comment by rph28** [comment]
Works fine for me

**Comment by FLYBYME** [comment]
Yeah Im getting the same issue

**Comment by bjwyse** [comment]
The protection on the User model is preventing the password from being encrypted when creating the admin user.

A workaround is to change `isProtected` to `false` for the user data in https://github.com/keystonejs/keystone-demo/blob/master/updates/0.0.1-admins.js#L13.

Then drop the database and restart. This was fine for me as I don't care about the user protection at all.

**Comment by jstockwin** [comment]
@bjwyse Is correct above. 
Authentication works fine at http://demo.keystonejs.com/, but when you clone it locally the protection is an issue.

If you're trying to get it to work locally, either edit the `updates/0.0.10admin.js` to remove line 13, and drop the database as suggested above, or simply add a new `updates/0.0.2-user.js` file, which is identical, but with different user credentials and again no line 13. That way you don't have to drop the database. 

I've created [an issue](https://github.com/keystonejs/keystone/issues/3801) on the keystone side of things to see if we can address encryption not working properly when `isProtected` is set to true.

If people have any insight into this/want to help fix it, let's pick this up on that issue.

**Comment by nouphaltklm** [comment]
Now the username & Password is user@keystonejs.com and admin. Installed via yo

**Comment by nouphaltklm** [comment]
Now the username & Password is **user@keystonejs.com** and **admin**. Installed via yo
