### ISSUE TITLE
Credentials for Admin UI are not working

### ISSUE THREAD

**Issue by viachaslau-taldykin** [keystonejs/keystone-demo#67]
Credentials for Admin UI are not working
Steps to reproduce:
1.  Go to http://demo.keystonejs.com/
2.  Click on "Sign in" button
3. enter username: **demo@keystonejs.com**, password: **demo**
**expected**: admin UI is opened.
**observed**: error message is shown ("_The email and password you entered are not valid._")

Thank you in advance

**Comment by stoplion** [comment]
Still not working.

**Comment by Vyz333** [comment]
I found when using "yo keystone" to generate the project my email got stored with a space in the middle e.g.: "user@domain.com" got stored as "user @domain.com", the wizard also ignored the password I specified and set the password to "admin".
Found out about the email by looking directly at the mongo database, the password I found about by mere luck.

**Comment by stennie** [comment]
Closing out old issues; this problem is no longer reproducible.

**Comment by Unsentletter** [comment]
I must be doing something wrong, but I am having this issue.
I have copy and pasted the email and passwords I used when I set up the app and it says they are not valid.
