### ISSUE TITLE
How  can  I use mysql in keystone instead of mongoDB?

### ISSUE THREAD

**Issue by gaofei019** [keystonejs/keystone-demo#75]
Hello, I shoule use mysql  in keystone instead of mongoDB.How to get it?

**Comment by export-mike** [comment]
this is not currently possible. We have however been looking/discussing options to be more agnostic in future keystone versions.

**Comment by bellsaladin** [comment]
I've started a project with the goal to support Mysql. The project has now a good foundation & implementation strategy.
https://github.com/bellsaladin/Keystone-Mysql

I have been using Keystone for quite a while now as light admin tool for some small projects and I aquired good knowledge on it's core functionning, at some point i felt the need for Mysql databases support, so i started a project with that goal.

I work on this project on free time only so I need help for this project to progress. **Any help is welcome**.
