### ISSUE TITLE
Remove Nitrous QuickStart from README.md

### ISSUE THREAD

**Issue by anpfeff** [keystonejs/keystone-demo#78]
Nitrous shutted down last year, therefore I would recommend to remove the section about Nitrous from `README.md`.
https://techcrunch.com/2016/10/31/cloud-development-platform-nitrous-io-shuts-down/

**Comment by stennie** [comment]
@anpfeff Thanks for the feedback (and apologies for the lengthy delay in response).

This has been fixed via #82.

Regards,
Stennie
