### ISSUE TITLE
Is there backend dashboard demo with Users module, Role base access controls, permission etc?

### ISSUE THREAD

**Issue by apvpn** [keystonejs/keystone-demo#89]
Looking for Keystonejs demo for admin backend where admin can login and manage users, its roles and give permissions for the roles with bootstrap4+ theme like adminLTE. it would help me to create interactive demo for my client.
Thanks in advance.

**Comment by stennie** [comment]
@apvpn The features you've described (dashboard, user management, ...) aren't core features of Keystone 4 or the Keystone demo project.

However, you might be interested in [ConnextCMS](http://connextcms.com/) which uses KeystoneJS as a backend and adds a frontend for user management and theming. It happens to use Bootstrap with AdminLTE.

NOTE: while ConnextCMS uses KeystoneJS, it is an independently maintained project and you should direct any questions to the developer.

Regards,
Stennie
