### ISSUE TITLE
keystone-demo v5 ? 

### ISSUE THREAD

**Issue by Asw20** [keystonejs/keystone-demo#93]
Hi,

This demo  is very well done. Is there the equivalence for the new version of keystone (V5) ?. The challenge I have with the current V5 demo application is that they does not porvide a the strucuture for a biggest application. ie like this demo I would like to see a folder structure.. How you organize your multiple models, functions etc... 

Regards,
Nicolas

**Comment by Noviny** [comment]
The best place to look would be our new [create-keystone-app](https://www.keystonejs.com/create-keystone-app/) which sets you up with a project in our preferred setup.

Let me know if this isn't what you were looking for.
